version: "3.8"
services:

  app-timesheet:
    depends_on:
      - mysql
    image: marwa2024/achat-1.0
    restart: on-failure
    ports:
      - "8987:8089"
    environment:
      SPRING_APPLICATION_JSON : '{
      "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/Achatdb?createDatabaseIfNotExist=true",
      "spring.datasource.username" : "root",
      "spring.datasource.password" : null,
      "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
      "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true


  mysql:
    image: "mysql:5.7"
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=Achatdb
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

volumes :
  db :